### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by purushottamshiwakoti** [viktorstrate/react-mathquill#59]
Uncaught ReferenceError: global is not defined
    at node_modules/react-mathquill/dist/react-mathquill.js (react-mathquill.js:18:4)
    at __require (chunk-UZX524IT.js?v=33be9258:3:50)
    at node_modules/react-mathquill/index.js (index.js:6:20)
    at __require (chunk-UZX524IT.js?v=33be9258:3:50)
    at index.js:7:1

**Comment by ProvotorOFF** [comment]
have the same problem

**Comment by wuguishifu** [comment]
@ProvotorOFF @purushottamshiwakoti 

this issue is caused by global being renamed to globalThis. You can temporarily fix this issue by adding 
```html
<script>const global = globalThis;</script>
```
to your `index.html` file.
